baseUrl: /
languageCode: en-us
theme: ["hugo-video", "terminal"]
paginate: 5

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: post
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: pink
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3
  # show selector to switch language
  showLanguageSelector: false
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: true

languages:
  en:
    languageName: English
    title: Jonte's Blog
    subtitle: Kinda epic shit
    keywords: 'linux, tech, technology, Jonatan Holmgren'
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts

    params:
      logo:
        logoText: Jonte's Page
        logoHomeLink: https://jontes.page

    menu:
      main:
      - identifier: blog
        name: Blog
        url: https://blog.jontes.page
      - identifier: github
        name: Github
        url: https://github.com/Jontes-Tech
